name: very_good_core
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  intl: ^0.18.0
  logger: ^2.0.1
  riverpod_annotation: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  riverpod_generator: ^2.2.6
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
